FROM openjdk:16.0.1-jdk
EXPOSE 8080
ADD /target/currency-conversion-service-0.0.1-SNAPSHOT.jar currency-conversion-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","currency-conversion-service-0.0.1-SNAPSHOT.jar"]